feat: implement require analyzer
Enapter/rockamalg pull request #14
Opened 2022-04-25 06:34 UTC by Pashnik

2022-04-25 13:46 UTC, kulti requested changes

2022-04-25 13:46 UTC, kulti commented on internal/rockamalgcli/cmd_amalg.go
> +						Isolate:      true,
А зачем тут включать изолированный режим? Думаю, лучше и здесь выдать настройку, т.к. можно запускать эту команду в докер контейнере с примонтированном вольюмом.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/rockamalg.go
> +	if sync {
Флаги нечитаемы в месте использования. Что такое `a.runCmd(cmd, true)`? Непонятно, пока не пойдешь читать сам метод. К тому же флаги часто означают, что метод делает несколько дел, а не одно, что нарушает принцип единой ответственности.

В данном случае, думаю, не будет большого вреда, если брать мьютекс всегда. Т.е. флаг вообще не нужен.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/rockamalg.go
> +	*sync.Mutex
Тут целая гора проблем.

Использование мьютекса стоит делать максимально узким, чтобы было очевидно, что именно он синхронизирует, где конкретно его используют.

Тут же он передается из одного объекта в другой. Протекание, размазывание зоны ответственности мьютекса. Такой эмбединг делать не стоит в принципе. Это протекание абстракции. amalg не является мьютексом по своему поведению.

Пока что в голову пришло такое решение — положить в `amalg` функцию `func(cmd *exec.Cmd) (*bytes.Buffer, error)`, а в `Rockamalg` назвать это мьютекс, чтобы было понятно, что он защищает от параллельного выполнения команд.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/rockamalg.go
> +	}
Если `analyzeRequires` провалился, нужен фоллбэк на isolate режим. Предлагаю это отдельным коммитом делать. Или, возможно, ты не забыл про это, и в процессе разработки понял, что он не нужен.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		return nil, err
Стоит врапнуть ошибки, иначе потом замучаемся разбираться, что пошло не так.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		req := toSee[i]
`for _, req := range toSee`

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		req := toSee[i]
Специально оставляю старый дискашен и пишу ответ к нему, после того, как разобрался, что тут происходит. Могу сказать следующее — 😱 🤯

Не надо так использовать циклы. Это интуитивно непонятно, запутанно, сложно. Проблема в том, что здесь условие выхода из цикла выглядит «просто», а на деле оно постоянно меняется. Такая же жесть получается, когда управляют счетчиком цикла где-то еще, кроме i++ в инструкции for. Суть в том, чтобы управление выходом из цикла было очевидным и в одном месте.

Например, здесь можно переделать логику в таком ключе:
```
for {
  // вызов функции, которая анализрует текущий список модулей и возвращает новый
  // если длинна списка осталась прежней, то break.
}
```

Возможно, в этом случае не нужно отдельно root анализировать. Т.е. этот цикл будет в `Analyzer::AnalyzeRequires`.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +func (a *analyzer) buildSourcePaths(require string) []string {
Зачем создавать слайс, выделять память, делать кучу копирований, чтобы потом все это выкинуть и оставить одно значение? Достаточно вернуть первый, который существует, т.е. объединить findSourceFile и buildSourcePaths в один метод.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +		return chunk{}, p.BuildError(errMissHeaderLine)
Заголовок уже распаршен. Думаю, тут другая ошибка должна быть. Пока не понимаю, что именно тут скипается.

В целом, врапинг ошибок выглядит так, что мы потом не разберемся, что тут происходит.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +	length, err := p.parseSegmentLength(name)
Я понял, чего тут не хватает. Нужно к функциям добавить док-стринг с примером, как выглядит то, что эта функция парсит.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +	upvalues, err := p.parseSegment("upvalues")
Могут ли сегменты в другом порядке быть?

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +	if len(fields) <= 1 {
`len(fields) < minOperands`

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +			fmt.Errorf("%w: instruction should have more then 1 operand, found: %d", errWrongTokensLength, len(fields))
`... should have at least %d operands..., minOperands`

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/resolver.go
> +func (i instruction) loadsRequire(envUpvalueID, reqConstID int) bool {
Это не похоже на метод для инструкции. Пока не понимаю, что тут имеется в виду.

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		return nil, err
`fmt.Errorf("generate bytecode: %w", err)`

2022-04-25 13:46 UTC, kulti commented on internal/rockamalg/analyzer/resolver.go
> +	return i.a == requireReg && i.a+1 == constantReg
Стоит еще проверить, что `i.b == 2`.

2022-04-26 13:15 UTC, kulti requested changes

2022-04-26 13:15 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		next, err := an.AnalyzeRequires(requires)
Мне кажется, что можно не делать an.Analyze несколькими строками выше, а начать с `requires := []string{luaMain}`.

2022-04-26 13:15 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +		nextReqs, err := a.Analyze(sf)
Думаю, этот метод нужно переименовать в `ExtractModuleRequires`/`LookupModuleRequires`. Analyze — слишком абстрактно.

2022-04-26 13:15 UTC, kulti commented on internal/rockamalg/analyzer/analyzer.go
> +			return nil, fmt.Errorf("require= %s, analyze: %w", req, err)
Зачем тут после `=` пробел? Либо двоеточие, либо пробел не нужен. На крайний случай пробел с двух сторон от равно.

И мне думается, что должно быть не require, а module. В `req` же имя модуля лежит.

2022-04-26 13:15 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +//	main <(string):0,0> (2 instructions at 00000029D9FA72D0)
Здесь (и во всех подобных местах далее) лишняя пустая строчка.

`listing example` висит в воздухе и ни к чему не относится, он сам по себе. Это из-за того, то пустая строка есть до и после. Он на одинаковом расстоянии находится, поэтому выглядит, как отдельный абзац. А это не так.

В комментариях мы не можем делать заголовки и разные межстрочные интервалы. Думаю, тут лучше удалить. Отступа в листингах достаточно, чтобы выделить.

2022-04-26 13:15 UTC, kulti commented on internal/rockamalg/analyzer/resolver.go
> +	checkHasRequire := func(i instruction) bool {
`checkIsRequire`.

2022-04-26 13:15 UTC, kulti commented on tests/integration/testdata/amalg/multi_files_more_modules/deps
> +lua-string ~> 1.2
А что значит "more"? Чем это принципиально отличается от старых тестов? Почему не добавить эти модули в старые тесты?

2022-04-26 13:15 UTC, kulti commented on tests/integration/testdata/amalg/multi_files_with_rockspec/stdout
> +Cleaning up result... Done
Вот это странно. Откуда очистка результатов в неизолированном режиме.

Думаю, дело в том, что нарушена плавность миграции. В режиме команды запуск был не изолированный, а тут он почему-то по умолчанию делается изолированным. В следующем коммите это исправляется. Думаю, можно забить. Лишь обратить внимание на некоторую нелогичность последовательности изменений, понять почему и в будущем чуть лучше делать.

2022-04-27 06:12 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +//	main <(string):0,0> (2 instructions at 00000029D9FA72D0)
Перед `listing example` я не предлагал удалить. Теперь описание сливается с примером. Пустые строки нужны, чтобы отделять друг от друга абзацы, смысловые куски. Также, как в коде. Здесь явно два куска — описание и пример. Возможно, даже три — краткое описание, подробности, пример.

2022-04-27 08:52 UTC, kulti approved these changes
Глаз немного замылился, если проблемы и есть, то будем чинить по ходу.

2022-04-27 08:52 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +// 	14	[5]	RETURN   	0 1
Т.к. тут есть вариативность, можно добавить несколько примеров. Разница же только в наличии/отсутствии комментария? Количество операндов на этот метод не влияют, но для порядка можно добавить.

Типа такого:
```
// parseInstructionLine parses single instruction line.
//
// instruction line examples:
// 	2	[1]	GETTABUP 	0 0 -1	; _ENV "require"
// 	14	[5]	RETURN   	0 1
```

2022-04-27 08:52 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +func (p *chunksParser) parseOperandsLine(line string) ([]int, error) {
Пришла такая идея:
```
func (p *chunksParser) parseOperandsLine(line string) (int, int, int, error) {
	const minOperands = 2
	fields := strings.Fields(line)

	if len(fields) < minOperands {
		return nil,
			fmt.Errorf("%w: instruction should have at least %d operands, found: %d",
				errWrongTokensLength, minOperands, len(fields),
			)
	}

	a, err := strconv.Atoi(fields[0])
	if err != nil {
		return 0, 0, 0, fmt.Errorf("convert a operand to int: %w", err)
	}

	b, err := strconv.Atoi(fields[1])
	if err != nil {
		return 0, 0, 0, fmt.Errorf("convert b operand to int: %w", err)
	}

	var c int
	if len(fields) >= minOperands {
		c, err = strconv.Atoi(fields[2])
		if err != nil {
			return 0, 0, 0, fmt.Errorf("convert c operand to int: %w", err)
		}
	}

	return a, b, c, nil
}
```

Тогда в parseInstructionLine не будет протекать информация о minOperands и присвоение будет в одну строчку, без условия.

Как вариант, можно заменить этот метод на `func (i *instruction) FillOperandsFromLine(line string) error`.

2022-04-27 08:52 UTC, kulti commented on internal/rockamalg/analyzer/parser.go
> +	const minTokens = 2
Тут тоже нужно больше примеров, чтобы было понятно, почему minTokens, а не tokensCount.

2022-04-27 08:52 UTC, kulti commented on tests/integration/testdata/amalg/multi_files_with_deps/fw_dir/main.lua
> +if x >= 10 then
Здесь можно наоборот < 10 сделать, чтобы другая ветка сработала.

2022-04-28 06:32 UTC, kulti commented on README.md
> +### Dependency caching
Вроде, мы обсуждали troubleshooting. Согласен, что стоит также рассказать, как ускорить работу 👍

Проблема этой секции в том, что ты на это смотришь глазами изнутри, а надо снаружи, с точки зрения пользователя. Ему неважно, как оно там устроено, про всякие аналайзеры. Ему важно, что эта штука ускоряет все. И важно знать, как ее включить.

Думаю, ее нужно вынести на один уровень выше и поместить после Server Mode. Внутри должно быть что-то такое:
```
### Dependency caching
Downloading dependencies for each amalgamation could take a lot of time. By default rockamalg uses dependency cache to speedup the amalgamation.

// показать, как запускать, чтобы кэш сохранялся между запусками (как вольюм примонтировать)

// подраздел про возможные проблемы, показать, как они проявляются, показать, как запускать, чтобы отключить этот режим кэширования
```

2022-04-29 09:24 UTC, kulti requested changes
Осталось чуть-чуть ридми допилить.

2022-04-29 09:24 UTC, kulti commented on README.md
> +amalg -o out.lua -d deps ucm.lua
Выглядит нечитаемо. Чтобы многострочный docker run хорошо выглядел, нужно отступы добавить. Пример — https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device.

2022-04-29 09:24 UTC, kulti commented on README.md
> +If you want to persist the cache between rockamalg runs, mount a volume into `/opt/rockamalg/.cache` in the container:
Downloading dependencies for each amalgamation could take a lot of time. Rockamalg caches dependencies to speedup the amalgamation.

You need to mount a volume into `/opt/rockamalg/.cache` to reuse cache between runs.

Single run:
```
...
```

Server mode:
```
...
```

2022-04-29 09:24 UTC, kulti commented on README.md
> +Sometimes when running an amalgamated file, you may encounter errors like:
Предлагаю упростить эту секцию до уровня пользователя.

Sometimes running result file can cause a error like:

```
...
```

It means, that rockamalg failed to detect all required Lua modules. In that case run rockamalg in *isolate mode* using `-i` flag:

```
...
```

2022-04-29 09:39 UTC, Pashnik commented on README.md
> +amalg -o out.lua -d deps ucm.lua
Брал за основу тот же docs.docker только для вольюмов, например: https://docs.docker.com/storage/volumes/#start-a-container-with-a-volume

2022-04-29 09:42 UTC, Pashnik commented on README.md
> +amalg -o out.lua -d deps ucm.lua
Ха, а если в самый низ промотать, то есть примеры с отступами

https://docs.docker.com/storage/volumes/#create-cifssamba-volumes

2022-04-29 14:09 UTC, kulti approved these changes

2022-04-29 14:10 UTC, merged