support custom rocks server
Enapter/rockamalg pull request #15
Opened 2022-04-29 09:57 UTC by Pashnik

2022-05-04 12:49 UTC, kulti requested changes

2022-05-04 12:49 UTC, kulti commented on internal/rockamalgcli/testdata/helps/rockamalg amalg
>     See the tutorial https://developers.enapter.com/docs/tutorial/lua-complex/introduction to learn more.
Думаю, этот коммит стоит посквошить с предыдущим, т.к. это связанные изменения — изменили код, старые тесты сразу же обновились. Новые тесты добавлять отдельным коммитом — нормально. Старые в идеале править вместе с тем кодом, который привел к изменениям в тестах, чтобы коммит сохранял консистентсность. Это не строгое правило, если из-за этого изменения сложные и громоздкие, то можно и ломать консистентсность на один-два коммита.

2022-05-04 12:49 UTC, kulti commented on tests/integration/amalg_test.go
>  func TestAmalgCommand(t *testing.T) {
Обсудили сделать два теста. Код теста вынести в приватную функцию.

2022-05-05 05:17 UTC, kulti requested changes

2022-05-05 05:17 UTC, kulti commented on README.md
> +	   -c "/opt/tools/pack_rocks.sh /opt/res lua-string inspect@3.1.2"
Можно скрипт в качестве `entyrpoint` указать. И, думаю, не нужно `/opt/res` передавать, т.к. output все равно задается на хосте через вольюм. 
```
docker run --rm \
	   -v $(pwd)/tests/integration/testdata/private-rocks/repository:/opt/res \
	   --entrypoint /opt/tools/pack_rocks.sh \
	   enapter/rockamalg \
	   lua-string inspect@3.1.2"
```

2022-05-05 05:17 UTC, kulti commented on tests/integration/testdata/amalg-private/single_file_with_deps/deps
> +myrock == dev-1
Такого луарока не существует на сервере. Т.е. `pack_rocks.sh` не сможет упаковать так, как сделано сейчас. Предлагаю использовать существующий луарок, а не писать свой.

2022-05-05 05:17 UTC, kulti commented on README.md
> +To pack rocks for integration tests use the `pack_rocks.sh` script:
Эта секция о том, как контрибьютить в rockamalg. Нужно указать реальные зависимости, необходимые для интеграционных тестов, а не абстрактные.

2022-05-05 07:39 UTC, kulti commented on README.md
> +	   -c "/opt/tools/pack_rocks.sh /opt/res lua-string inspect@3.1.2"
А что насчет `/opt/res` думаешь? Мне кажется, что ее можно не передавать, тогда только зависимости будут передаваться.

2022-05-05 08:31 UTC, Pashnik commented on README.md
> +	   -c "/opt/tools/pack_rocks.sh /opt/res lua-string inspect@3.1.2"
Поправил, чтобы `/opt/res` не передавать.

2022-05-05 09:05 UTC, kulti approved these changes

2022-05-05 09:17 UTC, merged